### PR TITLE
Add script to parse german Audible in MP3TAG

### PR DESCRIPTION
**Pull request by rabelux**

### CODE REVIEW

**Comment by rabelux** [comment]
Do you want to include different languages in your repo, or do you prefer them to be in other peoples' repos?

**Comment by seanap** [comment]
I think it'll be very helpful for me to include them in the main guide, but as a non speaker it will be hard for me to maintain if Audible updates their foreign sites.

**Comment by rabelux** [comment]
Thanks for including it! I also think your repo is the best spot to host it and I'm pretty sure the community will contribute if any adaptions are necessary.
In case the list keeps growing we could create a readme in this folder where maintainers are listed?

**Comment by seanap** [comment]
That is a great idea, that will help centralize the data so folks can find and keep up with their region

**Pull request merged**
